import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import moment from 'moment';
import { Toaster } from '@/components/ui/toaster';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <div className="flex flex-1 overflow-hidden">
          <Sidebar />
          <div className="w-full overflow-auto p-5 bg-gray-50">{children}</div>
        </div>
        <footer className="bg-black text-white p-4">
          © {moment().format('YYYY')} Music City Canada | Developed and
          maintained by Hector Robles
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
